services:
  metabase_db:
    image: postgres:17-alpine
    container_name: testing-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${FIRST_DB_NAME:-data_etl}
      POSTGRES_USER: ${FIRST_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${FIRST_DB_PASSWORD:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  pg_data:
